const cards = [
  { id: 1, content: '바보 카드 The Fool' },
  { id: 2, content: '마법사 카드 The Magician' },
  { id: 3, content: '여사제 카드 The High Priestess' },
  { id: 4, content: '여황제 카드 The Empress' },
  { id: 5, content: '황제 카드 The Emperor' },
  { id: 6, content: '교황 카드 The Hierophant' },
  { id: 7, content: '연인 카드 The Lovers' },
  { id: 8, content: '전차 카드 The Chariot' },
  { id: 9, content: '힘 카드 Strength' },
  { id: 10, content: '은둔자 카드 The Hermit' },
  { id: 11, content: '운명의 수레바퀴 Wheel of Fortune' },
  { id: 12, content: '정의 카드 Justice' },
  { id: 13, content: '매달린 남자 The Hanged Man' },
  { id: 14, content: '죽음 카드 Death' },
  { id: 15, content: '절제 카드 Temperance' },
  { id: 16, content: '악마 카드 The Devil' },
  { id: 17, content: '타워 카드 The Tower' },
  { id: 18, content: '별 카드 The Star' },
  { id: 19, content: '달 카드 The Moon' },
  { id: 20, content: '태양 카드 The Sun' },
  { id: 21, content: '심판 카드 Judgement' },
  { id: 22, content: '세계 카드 The World' },
  { id: 23, content: '에이스 완드 Ace of Wands' },
  { id: 24, content: '완드2 Two of Wands' },
  { id: 25, content: '완드3 Three of Wands' },
  { id: 26, content: '완드4 Four of Wands' },
  { id: 27, content: '완드5 Five of Wands' },
  { id: 28, content: '완드6 Six of Wands' },
  { id: 29, content: '완드7 Seven of Wands' },
  { id: 30, content: '완드8 Eight of Wands' },
  { id: 31, content: '완드9 Nine of Wands' },
  { id: 32, content: '완드10 Ten of Wands' },
  { id: 33, content: '완드 페이지 Page of Wands' },
  { id: 34, content: '완드 기사 Knight of Wands' },
  { id: 35, content: '완드 퀸 Queen of Wands' },
  { id: 36, content: '완드 킹 King of Wands' },
  { id: 37, content: '에이스 컵 Ace of Cups' },
  { id: 38, content: '컵2 Two of Cups' },
  { id: 39, content: '컵3 Three of Cups' },
  { id: 40, content: '컵4 Four of Cups' },
  { id: 41, content: '컵5 Five of Cups' },
  { id: 42, content: '컵6 Six of Cups' },
  { id: 43, content: '컵7 Seven of Cups' },
  { id: 44, content: '컵8 Eight of Cups' },
  { id: 45, content: '컵9 Nine of Cups' },
  { id: 46, content: '컵10 Ten of Cups' },
  { id: 47, content: '페이지 컵 Page of Cups' },
  { id: 48, content: '컵 기사 Knight of Cups' },
  { id: 49, content: '컵 퀸 Queen of Cups' },
  { id: 50, content: '컵 킹 King of Cups' },
  { id: 51, content: '소드 에이스 Ace Of Swords' },
  { id: 52, content: '소드2 Two Of Swords' },
  { id: 53, content: '소드3 Three of Swords' },
  { id: 54, content: '소드4 Four Of Swords' },
  { id: 55, content: '소드5 Five of Swords' },
  { id: 56, content: '소드6 Six of Swords' },
  { id: 57, content: '소드7 Seven of Swords' },
  { id: 58, content: '소드8 Eight Of Swords' },
  { id: 59, content: '소드9 Nine of Swords' },
  { id: 60, content: '소드10 Ten Of Swords' },
  { id: 61, content: '페이지 소드 Page of Swords' },
  { id: 62, content: '소드 나이트 Knight of Swords' },
  { id: 63, content: '소드 퀸 Queen of Swords' },
  { id: 64, content: '소드 킹 King Of Swords' },
  { id: 65, content: '에이스 펜타클 Ace of Pentacles' },
  { id: 66, content: '펜타클2 Two of Pentacles' },
  { id: 67, content: '펜타클3 Three of Pentacles' },
  { id: 68, content: '펜타클4 Four of Pentacles' },
  { id: 69, content: '펜타클5 Five of Pentacles' },
  { id: 70, content: '펜타클6 Six of Pentacles' },
  { id: 71, content: '펜타클7 Seven of Pentacles' },
  { id: 72, content: '펜타클8 Eight of Pentacles' },
  { id: 73, content: '펜타클9 Nine of Pentacles' },
  { id: 74, content: '펜타클10 Ten of Pentacles' },
  { id: 75, content: '페이지 펜타클 Page of Pentacles' },
  { id: 76, content: '펜타클 기사 Knight of Pentacles' },
  { id: 77, content: '펜타클 퀸 Queen of Pentacles' },
  { id: 78, content: '펜타클 킹 King of Pentacles' },
];
export default cards;
